name: Flutter Windows and macOS Build
on:
  push:
    branches:
      - main
    tags:
      - "*"
env:
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  DEVOPS_URL: ${{ secrets.DEVOPS_URL }}

jobs:
  build-windows:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Build for Windows
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          printenv | grep SENTRY_DSN > .env
          printenv | grep DEVOPS_URL >> .env
          flutter build windows
          7z a -r l10n_editor-windows.zip build/windows/runner/Release/*

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: l10n_editor-windows.zip
          path: l10n_editor-windows.zip

  build-macos:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Build for macOS
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          printenv | grep SENTRY_DSN > .env
          printenv | grep DEVOPS_URL >> .env
          flutter build macos
          zip l10n_editor-macos.zip -r build/macos/Build/Products/Release/l10n_manipulator.app/*
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: l10n_editor-macos.zip
          path: l10n_editor-macos.zip
